#!/usr/bin/python3

# This script parses the csv files generated by the Volksbank export function
# and outputs additional csv files which are understood by gnucash.

import csv
import re

transactions = list()

with open('raw.csv', 'r', newline='', encoding='latin1') as f:
    reader = csv.reader(f, delimiter=';')
    transactions = list(reader)[13:-3]

minus = [t for t in transactions if t[12] == 'S']
plus = [t for t in transactions if t[12] == 'H']

for name, transaction_list in [('minus', minus), ('plus', plus)]:
    transaction_list_t = list(zip(*transaction_list))
    filtered_t = [transaction_list_t[col_num] for col_num in [0,3,11]]
    filtered = list(zip(*filtered_t))
    formatted = list()
    for t in filtered:
        new_date = t[0].split('.')[2] + '-' + t[0].split('.')[1] + '-' + t[0].split('.')[0]
        new_amount = t[2]
        new_amount = re.sub('[.]', '', new_amount)
        new_amount = re.sub('[,]', '.', new_amount)
        formatted.append((new_date, t[1], new_amount))
    with open('{}.csv'.format(name), 'w', newline='') as f:
        writer = csv.writer(f, delimiter=',')
        writer.writerows(formatted)
